workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      android_signing:
        - myKeystore
      vars:
        PACKAGE_NAME: "com.anonymous.CodemagicSample"  # Replace with your actual package name
      node: 16.14.2
    scripts:
      - name: Install dependencies
        script: yarn install
      - name: Generate Android project (if missing)
        script: |
          npx expo prebuild || true
          echo "Listing project directory after expo prebuild:"
          ls -la
          if [ ! -d "android" ]; then
            echo "Error: android directory not found!"
            exit 1
          fi
      - name: Build Android app
        script: |
          echo "Current directory: $(pwd)"
          cd android || exit 1
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - t3hije01@students.oamk.fi
        notify:
          success: true
          failure: true