workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: windows
    environment:
      android_signing:
        - myKeystore
      vars:
        PACKAGE_NAME: "com.anonymous.CodemagicSample"  # Replace with your actual package name
      node: 18.18.2  # Updated Node.js version
    
    scripts:
      - name: Install dependencies
        script: yarn install

      - name: Generate Android project (if missing)
        script: |
          rmdir /s /q android  
          npx expo prebuild --clean --platform android || true
          dir 

      - name: Build Android app
        script: |
          echo "Current directory: %cd%"
          echo "Checking if android directory exists..."
          dir
          if not exist "android" (
            echo "Error: android directory NOT found!"
            exit 1
          )
          cd android
          gradlew.bat clean
          gradlew.bat assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - t3hije01@students.oamk.fi
        notify:
          success: true
