workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      android_signing:
        - myKeystore
      vars:
        PACKAGE_NAME: "com.anonymous.CodemagicSample"
      node: 18.18.2  # Updated to match Expo requirements

    scripts:
      - name: Install dependencies
        script: yarn install

      - name: Ensure Android project exists
        script: |
          rm -rf android 
          npx expo prebuild --clean --platform android
          echo "Checking if android directory exists..."
          ls -la
          if [ ! -d "android" ]; then
            echo "Error: android directory not created!"
            exit 1
          fi

      - name: Build Android app
        script: |
          echo "Current directory: $(pwd)"
          ls -la 
          if [ ! -d "android" ]; then
            echo "Error: android directory not found!"
            exit 1
          fi
          cd android
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - t3hije01@students.oamk.fi
        notify:
          success: true
          failure: true
